=== hzafar/paperclub/schema/topic.schema.json
{
    "$schema":"http://json-schema.org/draft-07/schema#",
    "title":"Topic",
    "description":"A CS topic or subtopic.",
    "type":"object",
    "properties": { 
        "id": {
            "description":"The classification number assigned to the topic/subtopic itself (not including broader terms).",
            "type":"string"
        },
        "name": {
            "description":"The name of the topic, as taken from the 2012 ACM Computing Classification.",
            "type":"string"
        },
        "broaderTerm": {
            "description":"Class number of parent topic.",
            "type":"string"
        },
        "narrowerTerms": {
            "type":"array",
            "items": {
                "type":"string"
            }
        }
    },
    "required": ["id", "name", "broaderTerm", "narrowerTerms"]
}

=== hzafar/paperclub/topic/theorycomp/logic/logic.topic.json
{
	"id": "10003790",
	"name": "Logic",
	"broaderTerm": "10003752",
	"narrowerTerms": [
		"10002990",
		"10003792",
		"10003793",
		"10003794",
		"10003795",
		"10003796",
		"10003797",
		"10003798",
		"10003799",
		"10003800",
		"10003801",
		"10003806",
		"10011119",
		"10011192",
		"10011740",
		"10011741",
		"10011742"
	]
}
